version: "3"
services: 
    fe:
        image: blog_post_fe
        ports:
          - 4200:80
    
    be:
        image: blog_post_be
        ports:
          - 4000:4000

    db:
        image: postgres:9.4
        environment:
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_PASSWORD: postgres
        volumes:
         - postgres:/var/lib/postgresql/data

volumes:
  postgres: